### ISSUE TITLE
[v0.2.6] SocketIoPrivateChannel should implement PrivateChannel

### ISSUE THREAD

**Issue by shinsenter** [kakajansh/echo#33]
I got an error after upgrading to v0.2.6.

```
Unhandled Exception: Unhandled error type 'SocketIoPrivateChannel' is not a subtype of type 'PrivateChannel' occurred.
Echo.private (package:laravel_echo/laravel_echo.dart:74:5) 
```

I viewed recent changes and found that SocketIoPrivateChannel does not implement PrivateChannel class.
https://github.com/kakajansh/echo/commit/b3d6740be3b5ae7078e36035b95da4a2778ef69d#diff-da850b311274c83f71e6393b096bbe7a24da7ad88b53c580250ed1bc1315f1a0

Could you please look into this? Thanks

**Comment by nicolasvahidzein** [comment]
Hey buddy,

how about you request this with a little bit more courtesy, you are coming off as extremely rude.

"Could you please look intot this? Thanks" would be much better.

Cheers

**Comment by shinsenter** [comment]
@nicolasvahidzein 
Sorry. That's my bad in choosing more polite words.

**Comment by nicolasvahidzein** [comment]
Not  problem @shinsenter thank you for your consideration. Have a good day.

**Comment by kakajansh** [comment]
Should be fixed, could you try with the latest version

**Comment by shinsenter** [comment]
@kakajansh 
Thank you. I works!
